//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::auth::Entity as Auth;
pub use super::buzz::Entity as Buzz;
pub use super::ratings::Entity as Ratings;
pub use super::reply::Entity as Reply;
pub use super::trending::Entity as Trending;
pub use super::users::Entity as Users;
