//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reply")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub buzz_id: i64,
    #[sea_orm(column_type = "Text")]
    pub reply_content: String,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub buzz_words: Option<String>,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub mentioned_users: Option<String>,
    pub ratings_id: Option<i64>,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::buzz::Entity",
        from = "Column::BuzzId",
        to = "super::buzz::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Buzz,
    #[sea_orm(
        belongs_to = "super::ratings::Entity",
        from = "Column::RatingsId",
        to = "super::ratings::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ratings,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::buzz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buzz.def()
    }
}

impl Related<super::ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ratings.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
