//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "trending")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub buzz_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub buzz_words: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::buzz::Entity",
        from = "Column::BuzzId",
        to = "super::buzz::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Buzz,
}

impl Related<super::buzz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buzz.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
